# Batch 3: ACL (5), NAT (4), Wireless (3), Trunking/Interface (4) = 16 cases

CASES = [
    # 6. ACCESS CONTROL LISTS (ACL) (5 cases)
    {
        "case_id": "NS-ACL-001",
        "title": "VLAN 30 PC Cannot Reach Server Due to Implicit Deny",
        "symptom": "PC in VLAN 30 has an IP address and can ping its default gateway 192.168.30.1, but cannot reach server 192.168.10.50 in VLAN 10.",
        "topology_note": "PC-30 (192.168.30.15) -> SW1 -> Router R1 -> Server-10 (192.168.10.50)",
        "show_outputs": "R1# show ip route 192.168.10.50\nRouting entry for 192.168.10.0/24\n Known via \"connected\", distance 0, metric 0 (connected)\n * directly connected, via GigabitEthernet0/0.10\n\nR1# show access-lists\nStandard IP access list BLOCK-OLD\n 10 permit 192.168.20.0, wildcard bits 0.0.0.255 (42 matches)\n (implicit deny any matches: 128)\n\nR1# show running-config interface GigabitEthernet0/0.10\ninterface GigabitEthernet0/0.10\n encapsulation dot1Q 10\n ip address 192.168.10.1 255.255.255.0\n ip access-group BLOCK-OLD out\n!",
        "expected_fault": "Outbound ACL 'BLOCK-OLD' on Gi0/0.10 only permits 192.168.20.0/24; VLAN 30 (192.168.30.0/24) traffic is dropped by the implicit deny any.",
        "osi_layer": "Layer 3/4 (Network / Transport)",
        "concept": "ACL",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show access-lists; show running-config interface Gi0/0.10",
        "expected_fix": "R1(config)# ip access-list standard BLOCK-OLD\nR1(config-std-nacl)# 20 permit 192.168.30.0 0.0.0.255\nR1(config-std-nacl)# exit",
        "verification_method": "ping 192.168.10.50 from PC-30 (success rate 100 percent)",
        "tags": "acl;access-list;implicit-deny;inter-vlan;packet-filtering"
    },
    {
        "case_id": "NS-ACL-002",
        "title": "Inverted Wildcard Mask in Extended ACL",
        "symptom": "Finance department workstations (10.10.50.0/24) cannot reach the ERP server at 10.20.10.100 on port 443.",
        "topology_note": "Finance PC (10.10.50.12) -> SW-Core -> R1 (Inbound ACL) -> ERP Server (10.20.10.100)",
        "show_outputs": "R1# show access-lists SECURE-ERP\nExtended IP access list SECURE-ERP\n 10 permit tcp 10.10.50.0 255.255.255.0 host 10.20.10.100 eq 443 (0 matches)\n 20 deny ip any any (354 matches)\n\nR1# show running-config interface GigabitEthernet0/0.50\ninterface GigabitEthernet0/0.50\n encapsulation dot1Q 50\n ip address 10.10.50.1 255.255.255.0\n ip access-group SECURE-ERP in\n!",
        "expected_fault": "The wildcard mask in ACL rule 10 was entered as a subnet mask '255.255.255.0' instead of Cisco inverse wildcard mask '0.0.0.255'.",
        "osi_layer": "Layer 3/4 (Network / Transport)",
        "concept": "ACL",
        "severity": "High",
        "difficulty": "Easy",
        "expected_next_command": "show access-lists SECURE-ERP",
        "expected_fix": "R1(config)# ip access-list extended SECURE-ERP\nR1(config-ext-nacl)# no 10\nR1(config-ext-nacl)# 10 permit tcp 10.10.50.0 0.0.0.255 host 10.20.10.100 eq 443\nR1(config-ext-nacl)# exit",
        "verification_method": "HTTPS connection from Finance PC to 10.20.10.100 succeeds; match counter increments on rule 10",
        "tags": "acl;wildcard-mask;inverse-mask;extended-acl;syntax-error"
    },
    {
        "case_id": "NS-ACL-003",
        "title": "ACL Applied in Wrong Direction (Outbound vs Inbound)",
        "symptom": "Management PC (172.16.1.10) cannot SSH to remote router loopback 10.255.255.1 despite ACL intending to permit SSH.",
        "topology_note": "Admin PC (172.16.1.10) -> Router R1 (Gi0/0) -> WAN",
        "show_outputs": "R1# show access-lists MGMT-FILTER\nExtended IP access list MGMT-FILTER\n 10 permit tcp host 172.16.1.10 any eq 22\n 20 deny ip any any (892 matches)\n\nR1# show running-config interface GigabitEthernet0/0\ninterface GigabitEthernet0/0\n ip address 172.16.1.1 255.255.255.0\n ip access-group MGMT-FILTER out\n!",
        "expected_fault": "ACL 'MGMT-FILTER' is applied with 'out' keyword on Gi0/0 instead of 'in'. It filters traffic exiting the interface toward the Admin PC rather than ingress traffic.",
        "osi_layer": "Layer 3/4 (Network / Transport)",
        "concept": "ACL",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show running-config interface Gi0/0",
        "expected_fix": "R1(config)# interface GigabitEthernet0/0\nR1(config-if)# no ip access-group MGMT-FILTER out\nR1(config-if)# ip access-group MGMT-FILTER in\nR1(config-if)# exit",
        "verification_method": "SSH from 172.16.1.10 connects; rule 10 match count increases",
        "tags": "acl;direction;inbound-outbound;interface-application"
    },
    {
        "case_id": "NS-ACL-004",
        "title": "Standard ACL Placed Too Close to Source",
        "symptom": "Applying an ACL to block Host A (10.0.1.10) from accessing Payroll Server (10.0.3.50) inadvertently blocked Host A from all other internal servers (Web, DNS).",
        "topology_note": "Host A (10.0.1.10) -> R1 (Gi0/0: Inbound ACL) -> Servers (VLAN 2: Web, VLAN 3: Payroll)",
        "show_outputs": "R1# show access-lists 10\nStandard IP access list 10\n 10 deny 10.0.1.10 (45 matches)\n 20 permit any (1200 matches)\n\nR1# show running-config interface GigabitEthernet0/0\ninterface GigabitEthernet0/0\n ip address 10.0.1.1 255.255.255.0\n ip access-group 10 in\n!",
        "expected_fault": "Standard ACL 10 (which filters only by source IP) was placed inbound near the source on Gi0/0, blocking Host A from all destinations instead of specifically the Payroll subnet.",
        "osi_layer": "Layer 3 (Network)",
        "concept": "ACL",
        "severity": "Medium",
        "difficulty": "Medium",
        "expected_next_command": "show access-lists 10; show running-config interface Gi0/0",
        "expected_fix": "R1(config)# interface GigabitEthernet0/0\nR1(config-if)# no ip access-group 10 in\nR1(config)# ip access-list extended BLOCK-PAYROLL\nR1(config-ext-nacl)# deny ip host 10.0.1.10 host 10.0.3.50\nR1(config-ext-nacl)# permit ip any any\nR1(config)# interface GigabitEthernet0/0\nR1(config-if)# ip access-group BLOCK-PAYROLL in",
        "verification_method": "Host A can reach Web/DNS servers; only Payroll server 10.0.3.50 is blocked",
        "tags": "acl;standard-acl;extended-acl;placement;over-filtering"
    },
    {
        "case_id": "NS-ACL-005",
        "title": "Missing Established Keyword in Return Traffic ACL",
        "symptom": "Internal users can send DNS queries, but external web browsing over HTTP/HTTPS fails as return web packets are blocked at the perimeter router.",
        "topology_note": "Internal LAN (192.168.1.0/24) -> R1 -> ISP WAN (Gi0/1)",
        "show_outputs": "R1# show access-lists INCOMING-TRAFFIC\nExtended IP access list INCOMING-TRAFFIC\n 10 permit udp any host 192.168.1.100 eq domain (520 matches)\n 20 deny ip any any (3145 matches)\n\nR1# show running-config interface GigabitEthernet0/1\ninterface GigabitEthernet0/1\n ip address 203.0.113.2 255.255.255.252\n ip access-group INCOMING-TRAFFIC in\n!",
        "expected_fault": "Inbound ACL on WAN interface has no 'permit tcp any 192.168.1.0 0.0.0.255 established' rule, causing all return TCP packets for client web sessions to be dropped.",
        "osi_layer": "Layer 4 (Transport / TCP Flags)",
        "concept": "ACL",
        "severity": "Critical",
        "difficulty": "Hard",
        "expected_next_command": "show access-lists INCOMING-TRAFFIC",
        "expected_fix": "R1(config)# ip access-list extended INCOMING-TRAFFIC\nR1(config-ext-nacl)# 15 permit tcp any 192.168.1.0 0.0.0.255 established\nR1(config-ext-nacl)# exit",
        "verification_method": "Web browsing from client to public web servers succeeds; rule 15 match count increases",
        "tags": "acl;tcp-established;return-traffic;firewall;stateless"
    },

    # 7. NAT & PAT (4 cases)
    {
        "case_id": "NS-NAT-001",
        "title": "Missing IP NAT Inside/Outside Interface Configuration",
        "symptom": "Internal hosts on 192.168.1.0/24 cannot reach the public internet (203.0.113.1) and NAT translation table is completely empty.",
        "topology_note": "LAN (192.168.1.0/24) -> R1 (Gi0/0 LAN, Gi0/1 WAN) -> Internet",
        "show_outputs": "R1# show ip nat translations\n(empty)\n\nR1# show ip nat statistics\nTotal active translations: 0 (0 static, 0 dynamic, 0 extended)\nOutside interfaces:\n none\nInside interfaces:\n GigabitEthernet0/0\nHits: 0 Misses: 0\n\nR1# show running-config interface GigabitEthernet0/1\ninterface GigabitEthernet0/1\n ip address 203.0.113.2 255.255.255.252\n!",
        "expected_fault": "WAN interface GigabitEthernet0/1 is missing the 'ip nat outside' command, preventing NAT translation evaluation.",
        "osi_layer": "Layer 3 (Network / NAT)",
        "concept": "NAT",
        "severity": "Critical",
        "difficulty": "Easy",
        "expected_next_command": "show ip nat statistics; show running-config interface Gi0/1",
        "expected_fix": "R1(config)# interface GigabitEthernet0/1\nR1(config-if)# ip nat outside\nR1(config-if)# exit",
        "verification_method": "show ip nat translations displays active NAT translations; ping 8.8.8.8 from LAN host succeeds",
        "tags": "nat;pat;nat-outside;translation-table;internet"
    },
    {
        "case_id": "NS-NAT-002",
        "title": "NAT Overload (PAT) Keyword Omitted",
        "symptom": "First user to open an internet connection succeeds, but all other simultaneous users immediately lose internet access.",
        "topology_note": "Office LAN (50 PCs) -> R1 (Gi0/1 Public IP 198.51.100.2) -> Internet",
        "show_outputs": "R1# show running-config | include ip nat\nip nat inside source list 1 interface GigabitEthernet0/1\naccess-list 1 permit 192.168.10.0 0.0.0.255\n\nR1# show ip nat translations\nPro Inside global Inside local Outside local Outside global\n--- 198.51.100.2 192.168.10.15 --- ---",
        "expected_fault": "The 'overload' keyword was omitted from the 'ip nat inside source list 1 interface Gi0/1' statement, creating a 1-to-1 dynamic NAT mapping that exhausts the single public IP.",
        "osi_layer": "Layer 3/4 (Network / Transport / PAT)",
        "concept": "NAT",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show running-config | include ip nat; show ip nat translations",
        "expected_fix": "R1(config)# no ip nat inside source list 1 interface GigabitEthernet0/1\nR1(config)# ip nat inside source list 1 interface GigabitEthernet0/1 overload",
        "verification_method": "show ip nat translations shows multiple UDP/TCP port bindings (PAT); all 50 hosts can browse concurrently",
        "tags": "nat;pat;overload;port-address-translation;capacity"
    },
    {
        "case_id": "NS-NAT-003",
        "title": "NAT Source ACL Does Not Match New Subnet",
        "symptom": "Hosts in original VLAN 10 (192.168.10.0/24) have full internet access, but hosts in newly added VLAN 20 (192.168.20.0/24) cannot reach the internet.",
        "topology_note": "VLAN 10 & VLAN 20 -> R1 (Router-on-a-stick) -> NAT Outbound Gi0/1",
        "show_outputs": "R1# show access-lists 1\nStandard IP access list 1\n 10 permit 192.168.10.0, wildcard bits 0.0.0.255 (2849 matches)\n\nR1# show running-config | include ip nat\nip nat inside source list 1 interface GigabitEthernet0/1 overload\ninterface GigabitEthernet0/0.10\n ip nat inside\ninterface GigabitEthernet0/0.20\n ip nat inside",
        "expected_fault": "Standard ACL 1 used for NAT only permits subnet 192.168.10.0/24; subnet 192.168.20.0/24 is not permitted in the NAT ACL.",
        "osi_layer": "Layer 3 (Network / NAT)",
        "concept": "NAT",
        "severity": "High",
        "difficulty": "Easy",
        "expected_next_command": "show access-lists 1",
        "expected_fix": "R1(config)# access-list 1 permit 192.168.20.0 0.0.0.255",
        "verification_method": "VLAN 20 hosts can ping internet IPs; ACL 1 match count increments for 192.168.20.0",
        "tags": "nat;nat-acl;standard-acl;pat;multi-vlan"
    },
    {
        "case_id": "NS-NAT-004",
        "title": "Static NAT Port Forwarding Wrong Inside IP",
        "symptom": "External customers cannot access public web portal at 203.0.113.10:80, even though internal web server at 192.168.1.80 is up and responding locally.",
        "topology_note": "External Clients -> Internet -> R1 (WAN 203.0.113.10) -> Web Server (192.168.1.80)",
        "show_outputs": "R1# show running-config | include ip nat inside source static\nip nat inside source static tcp 192.168.1.180 80 203.0.113.10 80 extendable\n\nR1# show ip arp | include 192.168.1.\nProtocol Address Age (min) Hardware Addr Type Interface\nInternet 192.168.1.80 4 0050.7966.6801 ARPA GigabitEthernet0/0",
        "expected_fault": "Static NAT port forwarding statement has a typo in the internal private IP (configured as 192.168.1.180 instead of real server IP 192.168.1.80).",
        "osi_layer": "Layer 3/4 (Network / Transport / Static NAT)",
        "concept": "NAT",
        "severity": "Critical",
        "difficulty": "Easy",
        "expected_next_command": "show running-config | include ip nat inside source static",
        "expected_fix": "R1(config)# no ip nat inside source static tcp 192.168.1.180 80 203.0.113.10 80 extendable\nR1(config)# ip nat inside source static tcp 192.168.1.80 80 203.0.113.10 80 extendable",
        "verification_method": "curl/browser test from external IP to http://203.0.113.10:80 returns HTTP 200 OK",
        "tags": "nat;static-nat;port-forwarding;dmz;web-server"
    },

    # 8. WIRELESS LAN (3 cases)
    {
        "case_id": "NS-WLAN-001",
        "title": "WPA2-PSK Key Mismatch on Wireless Client",
        "symptom": "Laptop-Wireless attempts to associate with SSID 'Corporate-WiFi' but fails at authentication stage and gets disconnected.",
        "topology_note": "Laptop-Wireless <---> (802.11ac) WAP-1 (Access Point) -> SW1 (VLAN 100)",
        "show_outputs": "WAP-1# show dot11 associations\n(no active associations)\n\nWAP-1# show running-config | section ssid\ndot11 ssid Corporate-WiFi\n vlan 100\n authentication open\n authentication key-management wpa2\n wpa-psk ascii CiscoSecure2026!\n\nLaptop-Wireless CLI:\nStatus: Authentication failed (code 4 - invalid preshared key entered 'Ciscosecure2026!')",
        "expected_fault": "Preshared key mismatch on wireless client due to case-sensitivity ('Ciscosecure2026!' vs AP key 'CiscoSecure2026!').",
        "osi_layer": "Layer 2 (Data Link / 802.11 Security)",
        "concept": "Wireless",
        "severity": "Medium",
        "difficulty": "Easy",
        "expected_next_command": "show dot11 associations on AP; inspect client WPA settings",
        "expected_fix": "Enter correct WPA2-PSK 'CiscoSecure2026!' on Laptop-Wireless profile.",
        "verification_method": "show dot11 associations shows Laptop MAC associated in state Authenticated; IP obtained via DHCP",
        "tags": "wireless;wpa2;wpa-psk;authentication;ssid;case-sensitive"
    },
    {
        "case_id": "NS-WLAN-002",
        "title": "AP Ethernet Port Configured as Access Instead of Trunk",
        "symptom": "Corporate wireless clients on SSID 'Corp-Data' (VLAN 10) can connect, but Guest clients on SSID 'Corp-Guest' (VLAN 20) fail to obtain IP addresses or pass traffic.",
        "topology_note": "Autonomous AP-1 (Multi-SSID) -> SW1 (Fa0/24) -> Router",
        "show_outputs": "SW1# show interfaces FastEthernet0/24 switchport\nName: Fa0/24\nSwitchport: Enabled\nAdministrative Mode: static access\nOperational Mode: static access\nAdministrative Trunking Encapsulation: dot1q\nOperational Trunking Encapsulation: native\nNegotiation of Trunking: Off\nAccess Mode VLAN: 10 (Corp-Data)\nTrunking Native Mode VLAN: 1 (default)\n\nAP-1# show running-config | section ssid\ndot11 ssid Corp-Data\n vlan 10\ndot11 ssid Corp-Guest\n vlan 20",
        "expected_fault": "Switch port Fa0/24 connected to multi-SSID Access Point is configured as an access port in VLAN 10 rather than an 802.1Q trunk port carrying both VLAN 10 and VLAN 20.",
        "osi_layer": "Layer 2 (Data Link / Trunking)",
        "concept": "Wireless",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show interfaces Fa0/24 switchport on SW1",
        "expected_fix": "SW1(config)# interface FastEthernet0/24\nSW1(config-if)# switchport mode trunk\nSW1(config-if)# switchport trunk allowed vlan 10,20\nSW1(config-if)# exit",
        "verification_method": "Guest clients on SSID Corp-Guest obtain 192.168.20.x IP address and can browse guest portal",
        "tags": "wireless;multi-ssid;trunk;ap-link;vlan-tagging"
    },
    {
        "case_id": "NS-WLAN-003",
        "title": "Wireless Client Band / Channel Mismatch (5GHz 802.11ac)",
        "symptom": "Legacy barcode scanner (2.4GHz 802.11b/g only) cannot see or discover the warehouse SSID 'Logistics-Scan'.",
        "topology_note": "Scanner (2.4GHz) <---> WAP-Warehouse (Radio 0: 2.4GHz disabled, Radio 1: 5GHz enabled)",
        "show_outputs": "WAP-Warehouse# show controllers dot11Radio 0\nDot11Radio 0 is administratively down (Frequency: 2.4 GHz)\n Status: shutdown\n\nWAP-Warehouse# show controllers dot11Radio 1\nDot11Radio 1 is up, line protocol is up (Frequency: 5.0 GHz)\n SSID: Logistics-Scan\n Channel: 36 (5180 MHz)",
        "expected_fault": "The 2.4GHz radio (Dot11Radio 0) is administratively shutdown on the AP, leaving only the 5GHz radio active which the legacy 2.4GHz client cannot detect.",
        "osi_layer": "Layer 1/2 (Physical / Wireless RF)",
        "concept": "Wireless",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show controllers dot11Radio 0; show controllers dot11Radio 1",
        "expected_fix": "WAP-Warehouse(config)# interface Dot11Radio 0\nWAP-Warehouse(config-if)# no shutdown\nWAP-Warehouse(config-if)# ssid Logistics-Scan\nWAP-Warehouse(config-if)# exit",
        "verification_method": "show controllers dot11Radio 0 is up; legacy scanner associates and receives IP",
        "tags": "wireless;rf;2.4ghz;5ghz;radio-shutdown;legacy-client"
    },

    # 9. TRUNKING & INTERFACE (4 cases)
    {
        "case_id": "NS-TRUNK-001",
        "title": "Native VLAN Mismatch on 802.1Q Trunk Link",
        "symptom": "CDP native VLAN mismatch warnings logged every 60 seconds; untagged traffic from VLAN 1 on SW1 arrives in VLAN 99 on SW2.",
        "topology_note": "SW1 (Gi0/1 Trunk) <---> (Gi0/1 Trunk) SW2",
        "show_outputs": "SW1# show log\n%CDP-4-NATIVE_VLAN_MISMATCH: Native VLAN mismatch discovered on GigabitEthernet0/1 (1), with SW2 GigabitEthernet0/1 (99).\n\nSW1# show interfaces GigabitEthernet0/1 trunk\nPort Mode Encapsulation Status Native vlan\nGi0/1 on 802.1q trunking 1\n\nSW2# show interfaces GigabitEthernet0/1 trunk\nPort Mode Encapsulation Status Native vlan\nGi0/1 on 802.1q trunking 99",
        "expected_fault": "Native VLAN mismatch across the trunk link: SW1 has Native VLAN 1 while SW2 has Native VLAN 99.",
        "osi_layer": "Layer 2 (Data Link)",
        "concept": "Trunking",
        "severity": "Medium",
        "difficulty": "Easy",
        "expected_next_command": "show interfaces Gi0/1 trunk on both switches",
        "expected_fix": "SW1(config)# interface GigabitEthernet0/1\nSW1(config-if)# switchport trunk native vlan 99\nSW1(config-if)# exit",
        "verification_method": "show log on SW1 and SW2 shows no further CDP native VLAN mismatch alerts",
        "tags": "trunking;native-vlan;cdp;dot1q;vlan-leak"
    },
    {
        "case_id": "NS-TRUNK-002",
        "title": "Required VLAN Not in Trunk Allowed List",
        "symptom": "Hosts in VLAN 50 connected to switch SW2 cannot communicate with servers in VLAN 50 on switch SW1 across trunk link Gi0/1.",
        "topology_note": "SW2 (VLAN 50 hosts) <--- Trunk Gi0/1 ---> SW1 (VLAN 50 servers)",
        "show_outputs": "SW1# show interfaces GigabitEthernet0/1 trunk\nPort Mode Encapsulation Status Native vlan\nGi0/1 on 802.1q trunking 1\n\nPort Vlans allowed on trunk\nGi0/1 1-40\n\nPort Vlans allowed and active in management domain\nGi0/1 1,10,20,30,40\n\nSW2# show vlan brief | include 50\n50 Engineering active Fa0/1, Fa0/2",
        "expected_fault": "Trunk interface Gi0/1 on SW1 restricts allowed VLANs to '1-40', pruning/blocking VLAN 50 traffic from traversing the trunk.",
        "osi_layer": "Layer 2 (Data Link)",
        "concept": "Trunking",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show interfaces Gi0/1 trunk",
        "expected_fix": "SW1(config)# interface GigabitEthernet0/1\nSW1(config-if)# switchport trunk allowed vlan add 50\nSW1(config-if)# exit",
        "verification_method": "show interfaces Gi0/1 trunk displays 50 in allowed list; ping between VLAN 50 hosts succeeds",
        "tags": "trunking;allowed-vlans;vlan-pruning;dot1q;inter-switch"
    },
    {
        "case_id": "NS-INT-001",
        "title": "Interface Administratively Shutdown",
        "symptom": "Entire branch office loses connection to HQ; line protocol and physical link LEDs on Router R1 WAN port Gi0/1 are off.",
        "topology_note": "R1 (Gi0/1 WAN: 192.168.100.2/30) <---> (Gi0/1: 192.168.100.1/30) R-HQ",
        "show_outputs": "R1# show ip interface brief | include GigabitEthernet0/1\nGigabitEthernet0/1 192.168.100.2 YES manual administratively down down \n\nR1# show interfaces GigabitEthernet0/1\nGigabitEthernet0/1 is administratively down, line protocol is down \n Hardware is CN Gigabit Ethernet, address is 0001.9654.1202\n Internet address is 192.168.100.2/30",
        "expected_fault": "Interface GigabitEthernet0/1 has the 'shutdown' command active in its configuration.",
        "osi_layer": "Layer 1 (Physical)",
        "concept": "Interface",
        "severity": "Critical",
        "difficulty": "Easy",
        "expected_next_command": "show ip interface brief",
        "expected_fix": "R1(config)# interface GigabitEthernet0/1\nR1(config-if)# no shutdown\nR1(config-if)# exit",
        "verification_method": "show ip interface brief shows GigabitEthernet0/1 up/up; ping 192.168.100.1 succeeds",
        "tags": "interface;administratively-down;shutdown;physical-layer;no-shutdown"
    },
    {
        "case_id": "NS-INT-002",
        "title": "Duplex Mismatch (Full Duplex vs Half Duplex)",
        "symptom": "Severe latency, excessive collisions, late collisions, and frame errors on uplink between switch SW1 and router R1.",
        "topology_note": "SW1 (Fa0/24 Full Duplex) <---> (Fa0/0 Half Duplex) R1",
        "show_outputs": "SW1# show interfaces FastEthernet0/24\nFastEthernet0/24 is up, line protocol is up\n Full-duplex, 100Mb/s, media type is 100BaseTX\n 0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored\n 0 late collision, 0 deferred\n\nR1# show interfaces FastEthernet0/0\nFastEthernet0/0 is up, line protocol is up\n Half-duplex, 100Mb/s, 100BaseTX/FX\n 2841 input errors, 1420 CRC, 912 frame, 0 overrun, 0 ignored\n 1890 late collisions, 2410 deferred, 0 lost carrier",
        "expected_fault": "Duplex mismatch: SW1 Fa0/24 is hardcoded to Full-Duplex while R1 Fa0/0 is hardcoded to Half-Duplex, causing collisions and frame drops under load.",
        "osi_layer": "Layer 2 (Data Link / MAC)",
        "concept": "Interface",
        "severity": "Medium",
        "difficulty": "Medium",
        "expected_next_command": "show interfaces Fa0/0 on R1; show interfaces Fa0/24 on SW1",
        "expected_fix": "R1(config)# interface FastEthernet0/0\nR1(config-if)# duplex full\nR1(config-if)# exit",
        "verification_method": "show interfaces Fa0/0 shows Full-duplex, 100Mb/s and late collisions cease increasing",
        "tags": "interface;duplex-mismatch;late-collisions;crc-errors;layer2"
    }
]