# Batch 2: DHCP (5), DNS (4), Routing (6) = 15 cases

CASES = [
    # 3. DHCP & DHCP RELAY (5 cases)
    {
        "case_id": "NS-DHCP-001",
        "title": "Missing IP Helper-Address for DHCP Relay",
        "symptom": "Client PCs in VLAN 10 fail to receive an IP address and fall back to APIPA (169.254.x.x). Central DHCP Server is located in VLAN 50.",
        "topology_note": "Clients (VLAN 10) -> SW1 -> Router R1 (Gi0/0.10 & Gi0/0.50) -> DHCP Server (192.168.50.10)",
        "show_outputs": "PC-1> ipconfig /all\nFastEthernet0 Connection:\n IP Address......................: 169.254.18.23\n Subnet Mask.....................: 255.255.0.0\n Default Gateway.................: 0.0.0.0\n DHCP Server.....................: 0.0.0.0\n\nR1# show running-config interface GigabitEthernet0/0.10\ninterface GigabitEthernet0/0.10\n encapsulation dot1Q 10\n ip address 192.168.10.1 255.255.255.0\n!\nR1# show running-config interface GigabitEthernet0/0.50\ninterface GigabitEthernet0/0.50\n encapsulation dot1Q 50\n ip address 192.168.50.1 255.255.255.0\n!",
        "expected_fault": "Router interface Gi0/0.10 is missing the 'ip helper-address 192.168.50.10' configuration to relay broadcast DHCP DISCOVER requests across subnets.",
        "osi_layer": "Layer 3/7 (Relay / DHCP)",
        "concept": "DHCP",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show running-config interface Gi0/0.10",
        "expected_fix": "R1(config)# interface GigabitEthernet0/0.10\nR1(config-subif)# ip helper-address 192.168.50.10\nR1(config-subif)# exit",
        "verification_method": "ipconfig /renew on PC-1 yields 192.168.10.x with gateway 192.168.10.1",
        "tags": "dhcp;helper-address;relay-agent;apipa;broadcast-forwarding"
    },
    {
        "case_id": "NS-DHCP-002",
        "title": "DHCP Pool Exhaustion",
        "symptom": "New workstations connecting to office network cannot obtain IP addresses. Existing workstations retain their addresses without issue.",
        "topology_note": "Clients -> SW1 -> R1 (Local IOS DHCP Server for 192.168.1.0/28)",
        "show_outputs": "R1# show ip dhcp pool\nPool LAN-POOL :\n Utilization mark (high/low) : 100 / 0\n Subnet size (total/usable) : 16 / 14\n Total addresses : 14\n Leased addresses : 14\n Excluded addresses : 0\n Pending event : none\n\nR1# show ip dhcp binding\nIP address Client-ID/Hardware address Lease expiration Type\n192.168.1.1 0100.0196.5412.01 Infinite Static\n192.168.1.2 0100.5079.6668.00 Mar 01 2026 12:00 AM Automatic",
        "expected_fault": "The DHCP pool subnet is sized at /28 (14 usable addresses) and all 14 addresses have been leased, exhausting the pool for new clients.",
        "osi_layer": "Layer 7 (Application / DHCP)",
        "concept": "DHCP",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show ip dhcp pool; show ip dhcp binding",
        "expected_fix": "R1(config)# ip dhcp pool LAN-POOL\nR1(config-dhcp)# network 192.168.1.0 255.255.255.0\nR1(config-dhcp)# default-router 192.168.1.1",
        "verification_method": "show ip dhcp pool shows total addresses > 100 and utilization < 20%",
        "tags": "dhcp;pool-exhaustion;ip-leases;capacity"
    },
    {
        "case_id": "NS-DHCP-003",
        "title": "DHCP Excluded Addresses Missing Gateway IP",
        "symptom": "Newly booted host was assigned IP 192.168.10.1 by DHCP, causing IP conflict and taking down the router default gateway.",
        "topology_note": "Host -> SW1 -> Router R1 (Gi0/0 192.168.10.1/24 serving DHCP)",
        "show_outputs": "R1# show running-config | section dhcp\nip dhcp pool POOL-A\n network 192.168.10.0 255.255.255.0\n default-router 192.168.10.1\n dns-server 8.8.8.8\n\nR1# show ip dhcp binding\nIP address Client-ID/Hardware address Lease expiration Type\n192.168.10.1 0100.0c8a.fe33.19 Feb 28 2026 04:15 PM Automatic\n\nR1# show log\n%IP-4-DUPADDR: Duplicate address 192.168.10.1 on GigabitEthernet0/0, sourced by 000c.8afe.3319",
        "expected_fault": "No 'ip dhcp excluded-address' statement was defined on the router, causing DHCP to offer the router's own interface IP 192.168.10.1 to clients.",
        "osi_layer": "Layer 7 (Application / DHCP)",
        "concept": "DHCP",
        "severity": "Critical",
        "difficulty": "Easy",
        "expected_next_command": "show running-config | section dhcp",
        "expected_fix": "R1(config)# ip dhcp excluded-address 192.168.10.1 192.168.10.10\nR1(config)# clear ip dhcp binding 192.168.10.1",
        "verification_method": "show ip dhcp binding no longer includes 192.168.10.1; client obtains 192.168.10.11+",
        "tags": "dhcp;excluded-address;ip-conflict;gateway-overlap"
    },
    {
        "case_id": "NS-DHCP-004",
        "title": "DHCP Option 3 (Default Gateway) Misconfigured",
        "symptom": "DHCP clients receive IP address and subnet mask correctly but cannot browse intranet servers outside their local subnet.",
        "topology_note": "Clients (10.0.100.0/24) -> SW1 -> Router R1 (Gateway 10.0.100.1)",
        "show_outputs": "Client> ipconfig /all\nFastEthernet0 Connection:\n IP Address......................: 10.0.100.22\n Subnet Mask.....................: 255.255.255.0\n Default Gateway.................: 10.0.100.254\n DHCP Server.....................: 10.0.100.1\n\nR1# show ip interface brief | include GigabitEthernet\nGigabitEthernet0/0 10.0.100.1 YES manual up up\n\nR1# show running-config | section dhcp\nip dhcp pool SALES-NET\n network 10.0.100.0 255.255.255.0\n default-router 10.0.100.254\n dns-server 10.0.100.5",
        "expected_fault": "The DHCP pool has option 3 configured as default-router 10.0.100.254, but the actual router gateway is 10.0.100.1.",
        "osi_layer": "Layer 7 (DHCP / Option 3)",
        "concept": "DHCP",
        "severity": "High",
        "difficulty": "Easy",
        "expected_next_command": "show running-config | section dhcp",
        "expected_fix": "R1(config)# ip dhcp pool SALES-NET\nR1(config-dhcp)# default-router 10.0.100.1\nR1(config-dhcp)# exit",
        "verification_method": "ipconfig /renew on client shows Default Gateway: 10.0.100.1; ping 10.0.100.1 succeeds",
        "tags": "dhcp;default-router;option-3;gateway-mismatch"
    },
    {
        "case_id": "NS-DHCP-005",
        "title": "DHCP Snooping Untrusted Uplink Port",
        "symptom": "DHCP clients connected to access switch SW2 fail to receive IP addresses after DHCP snooping was globally enabled on SW2.",
        "topology_note": "Clients -> SW2 (Gi0/1 Trunk Uplink) <---> SW1 (Core/DHCP Server)",
        "show_outputs": "SW2# show ip dhcp snooping\nSwitch DHCP snooping is enabled\nDHCP snooping is configured on following VLANs:\n10,20,30\nDHCP snooping option 82 is enabled\n\nSW2# show ip dhcp snooping binding\n(no bindings)\n\nSW2# show ip dhcp snooping interfaces\nInterface Trusted Rate limit (pps)\n----------------------- ------- ----------------\nFastEthernet0/1 no unlimited\nFastEthernet0/2 no unlimited\nGigabitEthernet0/1 no unlimited",
        "expected_fault": "DHCP snooping was enabled on SW2 without trusting the uplink trunk port Gi0/1 connected to the authorized DHCP server, blocking incoming DHCP OFFER and ACK packets.",
        "osi_layer": "Layer 2/7 (Security / DHCP)",
        "concept": "DHCP",
        "severity": "High",
        "difficulty": "Hard",
        "expected_next_command": "show ip dhcp snooping interfaces",
        "expected_fix": "SW2(config)# interface GigabitEthernet0/1\nSW2(config-if)# ip dhcp snooping trust\nSW2(config-if)# exit",
        "verification_method": "show ip dhcp snooping interfaces shows Gi0/1 Trusted: yes; clients receive IP addresses",
        "tags": "dhcp;dhcp-snooping;security;trusted-port;uplink"
    },

    # 4. DNS RESOLUTION (4 cases)
    {
        "case_id": "NS-DNS-001",
        "title": "Incorrect DNS Server IP Configured on Host",
        "symptom": "Users can ping external server IP 8.8.8.8 and internal server IP 172.16.5.10, but typing 'web.company.local' in browser fails with name resolution error.",
        "topology_note": "Host PC-1 -> SW1 -> R1 -> Internal DNS Server (172.16.5.53)",
        "show_outputs": "PC-1> ipconfig /all\nFastEthernet0 Connection:\n IP Address......................: 172.16.10.15\n Subnet Mask.....................: 255.255.255.0\n Default Gateway.................: 172.16.10.1\n DNS Server......................: 172.16.5.35\n\nPC-1> nslookup web.company.local\nDNS request timed out.\n timeout was 2 seconds.\n*** Can't find server name for address 172.16.5.35: Timed out\n\nPC-1> ping 172.16.5.53\nPinging 172.16.5.53 with 32 bytes of data:\nReply from 172.16.5.53: bytes=32 time=2ms TTL=126",
        "expected_fault": "DNS Server IP is mistyped as 172.16.5.35 instead of the valid DNS server IP 172.16.5.53.",
        "osi_layer": "Layer 7 (Application / DNS)",
        "concept": "DNS",
        "severity": "Medium",
        "difficulty": "Easy",
        "expected_next_command": "nslookup web.company.local 172.16.5.53",
        "expected_fix": "Update host / DHCP scope DNS server setting to 172.16.5.53",
        "verification_method": "nslookup web.company.local returns 172.16.5.10 successfully",
        "tags": "dns;name-resolution;nslookup;host-config;typo"
    },
    {
        "case_id": "NS-DNS-002",
        "title": "Missing DNS Domain-Lookup Command on Cisco IOS Router",
        "symptom": "Network administrator cannot ping domain names (e.g. 'ping time.nist.gov') from router CLI prompt.",
        "topology_note": "Router R1 (WAN Gi0/0) -> ISP Gateway 203.0.113.1",
        "show_outputs": "R1# ping time.nist.gov\nTranslating \"time.nist.gov\"...domain server (8.8.8.8)\n% Unrecognized host or address, or protocol not running.\n\nR1# show running-config | include ip name-server|ip domain\nno ip domain-lookup\nip name-server 8.8.8.8",
        "expected_fault": "DNS resolution is globally disabled on the router via 'no ip domain-lookup'.",
        "osi_layer": "Layer 7 (Application / DNS)",
        "concept": "DNS",
        "severity": "Low",
        "difficulty": "Easy",
        "expected_next_command": "show running-config | include domain",
        "expected_fix": "R1(config)# ip domain lookup",
        "verification_method": "ping time.nist.gov resolves and replies from R1",
        "tags": "dns;domain-lookup;ios;name-server"
    },
    {
        "case_id": "NS-DNS-003",
        "title": "Missing A Record on Authoritative DNS Server",
        "symptom": "Clients can resolve 'portal.corp.local' and 'mail.corp.local', but 'crm.corp.local' returns NXDOMAIN (Non-Existent Domain).",
        "topology_note": "Clients -> DNS Server (10.0.0.53) -> CRM Server (10.0.20.80)",
        "show_outputs": "Client> nslookup crm.corp.local\nServer: dc1.corp.local\nAddress: 10.0.0.53\n\n*** dc1.corp.local can't find crm.corp.local: Non-existent domain\n\nClient> ping 10.0.20.80\nReply from 10.0.20.80: bytes=32 time=3ms TTL=62",
        "expected_fault": "The DNS A-record for hostname 'crm.corp.local' is missing in the corp.local forward lookup zone on the DNS server.",
        "osi_layer": "Layer 7 (Application / DNS)",
        "concept": "DNS",
        "severity": "Medium",
        "difficulty": "Medium",
        "expected_next_command": "nslookup crm.corp.local 10.0.0.53",
        "expected_fix": "Add Host (A) record 'crm' pointing to 10.0.20.80 in zone corp.local on DNS Server.",
        "verification_method": "nslookup crm.corp.local returns 10.0.20.80",
        "tags": "dns;a-record;zone;nxdomain;server"
    },
    {
        "case_id": "NS-DNS-004",
        "title": "UDP Port 53 Blocked by Perimeter Firewall ACL",
        "symptom": "Internal hosts can resolve local internal hostnames via 10.0.0.53, but public internet FQDN resolution (e.g. google.com) fails.",
        "topology_note": "Internal DNS (10.0.0.53) -> Router R1 (ACL OUTSIDE-IN) -> Public DNS (1.1.1.1)",
        "show_outputs": "R1# show access-lists OUTSIDE-IN\nExtended IP access list OUTSIDE-IN\n 10 permit tcp any host 10.0.0.53 eq domain\n 20 permit icmp any any echo-reply\n 30 deny ip any any (1420 matches)\n\nR1# show ip nat translations | include :53\nudp 203.0.113.5:53342 10.0.0.53:53342 1.1.1.1:53 1.1.1.1:53",
        "expected_fault": "ACL OUTSIDE-IN only permits TCP port 53 and denies UDP port 53 return traffic required for standard DNS queries.",
        "osi_layer": "Layer 4/7 (Transport / DNS)",
        "concept": "DNS",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show access-lists OUTSIDE-IN",
        "expected_fix": "R1(config)# ip access-list extended OUTSIDE-IN\nR1(config-ext-nacl)# 15 permit udp any host 10.0.0.53 eq domain\nR1(config-ext-nacl)# exit",
        "verification_method": "nslookup cisco.com from client resolves successfully",
        "tags": "dns;udp53;acl;firewall;transport"
    },

    # 5. ROUTING & OSPF/STATIC (6 cases)
    {
        "case_id": "NS-ROUT-001",
        "title": "Missing Default Static Route on Edge Router",
        "symptom": "Branch office PCs can reach local subnets and HQ over VPN, but cannot reach any internet websites (e.g. 8.8.8.8 or 208.67.222.222).",
        "topology_note": "Branch PCs -> R-Branch (Gi0/0) -> (Gi0/1 WAN: 198.51.100.2) <---> (198.51.100.1) ISP Router",
        "show_outputs": "R-Branch# show ip route\nGateway of last resort is not set\n 10.0.0.0/8 is variably subnetted, 2 subnets, 2 masks\nC 10.5.10.0/24 is directly connected, GigabitEthernet0/0\nL 10.5.10.1/32 is directly connected, GigabitEthernet0/0\n 198.51.100.0/30 is subnetted, 2 subnets\nC 198.51.100.0/30 is directly connected, GigabitEthernet0/1\nL 198.51.100.2/32 is directly connected, GigabitEthernet0/1\n\nR-Branch# ping 8.8.8.8\nSuccess rate is 0 percent (0/5)",
        "expected_fault": "No default static route (ip route 0.0.0.0 0.0.0.0 198.51.100.1) is configured, leaving Gateway of last resort not set.",
        "osi_layer": "Layer 3 (Network)",
        "concept": "Routing",
        "severity": "Critical",
        "difficulty": "Easy",
        "expected_next_command": "show ip route",
        "expected_fix": "R-Branch(config)# ip route 0.0.0.0 0.0.0.0 198.51.100.1",
        "verification_method": "show ip route shows 'Gateway of last resort is 198.51.100.1'; ping 8.8.8.8 succeeds (5/5)",
        "tags": "routing;default-route;static-route;gateway-of-last-resort;internet"
    },
    {
        "case_id": "NS-ROUT-002",
        "title": "OSPF Area ID Mismatch Preventing Neighbor Adjacency",
        "symptom": "Routers R1 and R2 are directly connected via Gi0/0/0, but OSPF neighbor adjacency is not forming and routes are not exchanged.",
        "topology_note": "R1 (Gi0/0/0: 10.1.12.1/30) <---> (Gi0/0/0: 10.1.12.2/30) R2",
        "show_outputs": "R1# show ip ospf neighbor\n(blank output - no neighbors)\n\nR1# show ip ospf interface GigabitEthernet0/0/0\nGigabitEthernet0/0/0 is up, line protocol is up\n Internet Address 10.1.12.1/30, Area 0, Attached via Interface Enable\n Process ID 1, Router ID 1.1.1.1, Network Type BROADCAST, Cost: 1\n\nR2# show ip ospf interface GigabitEthernet0/0/0\nGigabitEthernet0/0/0 is up, line protocol is up\n Internet Address 10.1.12.2/30, Area 1, Attached via Interface Enable\n Process ID 1, Router ID 2.2.2.2, Network Type BROADCAST, Cost: 1",
        "expected_fault": "OSPF Area mismatch on interconnect link: R1 is in Area 0 while R2 is in Area 1.",
        "osi_layer": "Layer 3 (Network)",
        "concept": "Routing",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show ip ospf interface Gi0/0/0 on both routers",
        "expected_fix": "R2(config)# router ospf 1\nR2(config-router)# no network 10.1.12.0 0.0.0.3 area 1\nR2(config-router)# network 10.1.12.0 0.0.0.3 area 0",
        "verification_method": "show ip ospf neighbor shows state FULL/BDR; show ip route shows O routes",
        "tags": "routing;ospf;area-mismatch;neighbor-adjacency;layer3"
    },
    {
        "case_id": "NS-ROUT-003",
        "title": "OSPF MTU Mismatch Stuck in EXSTART/EXCHANGE State",
        "symptom": "OSPF adjacency between R1 and R3 is stuck in EXSTART state and routing table never populates remote subnets.",
        "topology_note": "R1 (Gi0/1 MTU 1500) <---> R3 (Gi0/1 MTU 1400)",
        "show_outputs": "R1# show ip ospf neighbor\nNeighbor ID Pri State Dead Time Address Interface\n3.3.3.3 1 EXSTART/DR 00:00:36 10.1.13.2 GigabitEthernet0/1\n\nR1# show interfaces GigabitEthernet0/1 | include MTU\n MTU 1500 bytes, BW 1000000 Kbit/sec, DLY 10 usec\n\nR3# show interfaces GigabitEthernet0/1 | include MTU\n MTU 1400 bytes, BW 1000000 Kbit/sec, DLY 10 usec\n\nR1# show log | include OSPF\n%OSPF-5-ADJCHG: Process 1, Nbr 3.3.3.3 on GigabitEthernet0/1 from LOADING to FULL, Bad Length in DBD",
        "expected_fault": "MTU mismatch on link (1500 bytes on R1 vs 1400 bytes on R3) causes OSPF Database Description (DBD) packets to be dropped, stalling state in EXSTART.",
        "osi_layer": "Layer 3 (Network)",
        "concept": "Routing",
        "severity": "High",
        "difficulty": "Hard",
        "expected_next_command": "show interfaces Gi0/1 | include MTU",
        "expected_fix": "R3(config)# interface GigabitEthernet0/1\nR3(config-if)# ip mtu 1500\nR3(config-if)# exit",
        "verification_method": "show ip ospf neighbor shows FULL/DR state",
        "tags": "routing;ospf;mtu-mismatch;exstart;dbd-packet"
    },
    {
        "case_id": "NS-ROUT-004",
        "title": "Static Route Next-Hop Unreachable / Recursive Failure",
        "symptom": "Host in 192.168.1.0/24 cannot ping Server in 10.50.0.0/16 despite static route configured on Router R1.",
        "topology_note": "Client -> R1 (Gi0/0 192.168.1.1/24) -- R1 (Gi0/1 172.16.1.1/30) <---> R2",
        "show_outputs": "R1# show ip route static\nGateway of last resort is not set\nS 10.50.0.0/16 [1/0] via 172.16.2.2\n\nR1# show ip route 172.16.2.2\n% Network not in table\n\nR1# show ip interface brief | include GigabitEthernet\nGigabitEthernet0/0 192.168.1.1 YES manual up up\nGigabitEthernet0/1 172.16.1.1 YES manual up up",
        "expected_fault": "Static route next-hop 172.16.2.2 is unreachable because the directly connected transit network is 172.16.1.0/30 (R2 is at 172.16.1.2).",
        "osi_layer": "Layer 3 (Network)",
        "concept": "Routing",
        "severity": "High",
        "difficulty": "Medium",
        "expected_next_command": "show ip route 172.16.2.2; show ip interface brief",
        "expected_fix": "R1(config)# no ip route 10.50.0.0 255.255.0.0 172.16.2.2\nR1(config)# ip route 10.50.0.0 255.255.0.0 172.16.1.2",
        "verification_method": "show ip route shows 10.50.0.0/16 via 172.16.1.2 active in RIB; ping 10.50.0.10 succeeds",
        "tags": "routing;static-route;next-hop;recursive-routing;unreachable"
    },
    {
        "case_id": "NS-ROUT-005",
        "title": "Passive Interface Configured on Active Routing Link",
        "symptom": "Branch router R-Branch does not form OSPF adjacency with Distribution router R-Dist over link Gi0/0.",
        "topology_note": "R-Branch (Gi0/0) <---> (Gi0/0) R-Dist",
        "show_outputs": "R-Dist# show ip ospf neighbor\n(blank output)\n\nR-Branch# show running-config | section router ospf\nrouter ospf 1\n router-id 10.99.99.1\n passive-interface GigabitEthernet0/0\n network 10.0.12.0 0.0.0.3 area 0\n network 10.10.0.0 0.0.255.255 area 0\n\nR-Branch# show ip ospf interface GigabitEthernet0/0\nGigabitEthernet0/0 is up, line protocol is up\n Internet Address 10.0.12.1/30, Area 0\n Process ID 1, Router ID 10.99.99.1, Network Type BROADCAST, Cost: 1\n No Hellos (Passive interface)",
        "expected_fault": "Interface Gi0/0 is erroneously configured as passive-interface, suppressing OSPF Hello packet transmission on the router-to-router link.",
        "osi_layer": "Layer 3 (Network)",
        "concept": "Routing",
        "severity": "High",
        "difficulty": "Easy",
        "expected_next_command": "show ip ospf interface Gi0/0",
        "expected_fix": "R-Branch(config)# router ospf 1\nR-Branch(config-router)# no passive-interface GigabitEthernet0/0",
        "verification_method": "show ip ospf neighbor shows FULL state; Hello packets sent out Gi0/0",
        "tags": "routing;ospf;passive-interface;hello-packets;adjacency"
    },
    {
        "case_id": "NS-ROUT-006",
        "title": "Asymmetric Routing Causing TCP Connection Reset",
        "symptom": "Ping succeeds between Host A (10.1.1.50) and Host B (10.2.2.50), but SSH/HTTP TCP connections freeze or reset immediately.",
        "topology_note": "Host A -> R1 -> Firewall FW1 -> R2 -> Host B | Return path: Host B -> R2 -> R3 -> R1 (bypassing stateful FW1)",
        "show_outputs": "R2# show ip route 10.1.1.0\nRouting entry for 10.1.1.0/24\n Known via \"ospf 1\", distance 110, metric 20, type intra area\n * 10.3.3.1 (via GigabitEthernet0/2 towards R3)\n\nR1# show ip route 10.2.2.0\nRouting entry for 10.2.2.0/24\n Known via \"ospf 1\", distance 110, metric 20, type intra area\n * 10.12.1.2 (via GigabitEthernet0/1 towards Firewall FW1)\n\nFW1# show log | include TCP-DROP\n%ASA-6-106015: Deny TCP (no connection) from 10.1.1.50/49152 to 10.2.2.50/22 on interface INSIDE",
        "expected_fault": "Asymmetric routing path causes return TCP SYN-ACK traffic to bypass the stateful firewall FW1, resulting in TCP teardown.",
        "osi_layer": "Layer 3/4 (Network / Transport)",
        "concept": "Routing",
        "severity": "Critical",
        "difficulty": "Hard",
        "expected_next_command": "traceroute from both directions; show ip route on R1 and R2",
        "expected_fix": "Adjust OSPF interface cost on R2 Gi0/2 so symmetric path through Firewall link Gi0/1 is preferred in both directions.",
        "verification_method": "SSH from Host A to Host B connects cleanly; traceroute is symmetric",
        "tags": "routing;asymmetric-routing;firewall;stateful;tcp-reset"
    }
]