"""SQLAlchemy model for Diagnoses."""

from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Text, DateTime
from database.database import Base


class DiagnosisModel(Base):
    """Network Diagnosis Entity generated by NetSage AI."""

    __tablename__ = "diagnoses"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    case_id = Column(String(50), index=True, nullable=True)
    symptom = Column(Text, nullable=True)
    topology_note = Column(Text, nullable=True)
    show_output = Column(Text, nullable=True)
    root_cause = Column(Text, nullable=False)
    confidence = Column(Float, nullable=False)
    osi_layer = Column(String(20), nullable=False)
    evidence = Column(Text, nullable=False)  # Stored as JSON string list
    next_command = Column(Text, nullable=False)
    fix_steps = Column(Text, nullable=False)  # Stored as JSON string list
    rule_results = Column(Text, nullable=False)  # Stored as JSON string list
    review_status = Column(String(30), default="Pending Review", nullable=False)
    dataset_status = Column(String(30), default="SAMPLE", nullable=False)
    ai_mode = Column(String(20), default="mock", nullable=False)
    evidence_grounding_status = Column(String(30), default="Unverified", nullable=False)
    grounded_evidence = Column(Text, nullable=True)  # Stored as JSON string list
    created_at = Column(DateTime, default=datetime.utcnow)
